version: "2"

services:
  php:
    build: ./docker/images/php-7.3
    image: php:7.3-app
    container_name: app-php
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/data:/data
      - ./docker/scripts:/docker/scripts
      - ./docker/conf/apache/sites-available:/etc/apache2/sites-available:ro
      - ./docker/logs/apache/:/var/log/apache2:delegated
      - ./docker/logs/php/:/var/log/php:delegated
      - ./docker/logs/xdebug:/var/log/xdebug/:delegated
    networks:
      - app-network
    expose:
      - 80
      - 443
      - 9000
    ports:
      - "80:80"
      - "443:443"
    tty: true

  mariadb:
    image: mariadb:10.3
    container_name: app-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_CHARSET=utf8
      - MYSQL_COLLATION=utf8_czech_ci
    volumes:
      - app-db-volume:/var/lib/mysql:delegated
      - ./docker/conf/mysql/:/etc/mysql/:ro
      - ./docker/sql:/data:ro
      - ./docker/logs/mysql:/var/log/mysql/:delegated
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3306:3306"

#  redis:
#    image: redis:alpine
#    container_name: app-redis
#    volumes:
#      - app-redis-volume:/data
#    entrypoint: redis-server --appendonly yes
#    networks:
#      - app-network
#    expose:
#      - 6379
#    ports:
#      - "6379:6379"
#
#  elasticsearch:
#    image: elasticsearch:5.6-alpine
#    container_name: app-elasticsearch
#    volumes:
#      - app-elasticsearch-volume:/usr/share/elasticsearch/data
#    expose:
#      - 9200
#    ports:
#      - "9200:9200"
#    networks:
#      - app-network
#
#  memcached:
#    image: memcached:alpine
#    container_name: app-memcached
#    networks:
#      - app-network



volumes:
  app-db-volume:
  app-redis-volume:
  app-elasticsearch-volume:



networks:
  app-network: